service: serverless-beasties-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    USER_TABLE: Beasties-user-${self:provider.stage}
    ANIMAL_TABLE: Beasties-animal-${self:provider.stage}
    USER_ANIMAL_REQUESTS_TABLE: Beasties-request-${self:provider.stage}
  
  tracing:
    lambda: true
    apiGateway: true

custom:
  topicName: beasties-${self:provider.stage}
  documentation:
    api:
      info:
        version: v1.0.0
        title: Beasties API
        description: API for Beasties application
    models:
      - name: CreateUserAPIRequest
        contentType: application/json
        schema: ${file(models/create-user.json)}
      - name: CreateAnimalAPIRequest
        contentType: application/json
        schema: ${file(models/create-animal.json)}
      - name: CreateRequestAPIRequest
        contentType: application/json
        schema: ${file(models/create-request.json)}
      - name: UpdateRequest
        contentType: application/json
        schema: ${file(models/update-requestStatus.json)}

functions:
  
  CreateUser:
    handler: src/lambda/http/createUser.handler
    events:
      - http:
          method: post
          path: user
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new user
            description: Create a regular user or shelter user
            requestModels:
              'application/json': CreateUserAPIRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_TABLE}
  
  CreateAnimal:
    handler: src/lambda/http/createAnimal.handler
    events:
      - http:
          method: post
          path: animal
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new animal
            description: Create a pet animal
            requestModels:
              'application/json': CreateAnimalAPIRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ANIMAL_TABLE}
  
  CreateRequest:
    handler: src/lambda/http/createRequest.handler
    events:
      - http:
          method: post
          path: request
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new request
            description: Create an adoption/date request for an animal
            requestModels:
              'application/json': CreateRequestAPIRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_ANIMAL_REQUESTS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_TABLE}
      - Effect: Allow
        Action:
          - execute-api:Invoke
        Resource: arn:aws:execute-api:*:*:*
  
  GetUserByUserName:
    handler: src/lambda/http/getUserByUsername.handler
    events:
      - http:
          method: get
          path: user/{userName}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_TABLE}
  
  GetAnimalByNameAndShelter:
    handler: src/lambda/http/getAnimalByNameAndShelter.handler
    events:
      - http:
          method: get
          path: animals/{animalName}/{shelterName}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ANIMAL_TABLE}
  
  GetAllRequestsForUser:
    handler: src/lambda/http/getAllRequestsForUser.handler
    events:
      - http:
          method: get
          path: request/{userName}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_ANIMAL_REQUESTS_TABLE}

  GetRequestsForUser:
    handler: src/lambda/http/getRequestsForUser.handler
    events:
      - http:
          method: get
          path: request/{userName}/{requestStatus}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_ANIMAL_REQUESTS_TABLE}

  GetPendingReqForShelter:
    handler: src/lambda/http/getPendingReqForShelter.handler
    events:
      - http:
          method: get
          path: requestsForShelterOwner/{shelterName}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/*

  GetRequestsForPet:
    handler: src/lambda/http/getRequestsForPet.handler
    events:
      - http:
          method: get
          path: requestsForPet/{animalName}/{shelterName}/{requestStatus}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/*
  
  GetRequestDetails:
    handler: src/lambda/http/getRequestDetails.handler
    events:
      - http:
          method: get
          path: requestDetails/{userName}/{shelterName}/{animalName}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:Scan
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/*
  
  UpdateRequestByShelter:
    handler: src/lambda/http/updateRequestByShelter.handler
    events:
      - http:
          method: patch
          path: requestEditByShelter/{shelterOwnerName}/{customerName}/{shelterName}/{animalName}
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Update the requestStatus of a pet by shelter
            description: Update an existing post item
            requestModels:
              'application/json': UpdateRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/*
      - Effect: Allow
        Action:
          - execute-api:Invoke
        Resource: arn:aws:execute-api:*:*:*
  
  DeleteRequest:
    handler: src/lambda/http/deleteRequest.handler
    events:
      - http:
          method: delete
          path: requestDelete/{userName}/{shelterName}/{animalName}
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/*

resources:
  Resources:
    #User-Table
    BeastiesUserDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    #Animal-Table
    BeastiesAnimalDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ANIMAL_TABLE}
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: shelterName
            AttributeType: S
          - AttributeName: animalName_shelterName
            AttributeType: S
        KeySchema:
          - AttributeName: animalName_shelterName
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: shelterAnimalNameGSI
            KeySchema:
              - AttributeName: shelterName
                KeyType: HASH
              - AttributeName: type
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        
        
    #User-Animal-Request-Table
    BeastiesRequestsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_ANIMAL_REQUESTS_TABLE}
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
          - AttributeName: shelterName
            AttributeType: S
          - AttributeName: animalName
            AttributeType: S
          - AttributeName: animalName_shelterName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
          - AttributeName: animalName_shelterName
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: requestsGSI
            KeySchema:
              - AttributeName: shelterName
                KeyType: HASH
              - AttributeName: animalName
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    #Request body validator
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
      
    #Api gateway Response Default 4xx
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi