service:
  name: serverless-beasties-app

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    USER_TABLE: Beasties-user-${self:provider.stage}
    ANIMAL_TABLE: Beasties-animal-${self:provider.stage}
    USER_ANIMAL_REQUESTS_TABLE: Beasties-requests-${self:provider.stage}
  
  tracing:
    lambda: true
    apiGateway: true

resources:
  Resources:
    #User-Table
    BeastiesUserDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    #Animal-Table
    BeastiesAnimalDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ANIMAL_TABLE}
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: shelterName
            AttributeType: S
          - AttributeName: animalName_shelterName
            AttributeType: S
        KeySchema:
          - AttributeName: animalName_shelterName
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: shelterAnimalNameGSI
            KeySchema:
              - AttributeName: shelterName
                KeyType: HASH
              - AttributeName: type
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        
        
    #User-Animal-Request-Table
    BeastiesRequestsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_ANIMAL_REQUESTS_TABLE}
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
          - AttributeName: shelterName
            AttributeType: S
          - AttributeName: animalName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: requestsGSI
            KeySchema:
              - AttributeName: shelterName
                KeyType: HASH
              - AttributeName: animalName
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST